### ISSUE TITLE
File is not a constructor

### ISSUE THREAD

**Issue by LwiDev** [Nedinator/djs-commands#2]
The console displays this when I launch my bot.

C:\Users\---\Desktop\IVL\Discord\Bots\JavaScript\Maya\V2\node_modules\djs-commands\CommandHandler.js:29
            const cmd = new file();
                        ^

TypeError: file is not a constructor
    at CommandHandler._loadFrom (C:\Users\---\Desktop\IVL\Discord\Bots\JavaScript\Maya\V2\node_modules\djs-commands\CommandHandler.js:29:25)
    at new CommandHandler (C:\Users\---\Desktop\IVL\Discord\Bots\JavaScript\Maya\V2\node_modules\djs-commands\CommandHandler.js:9:14)
    at Object.<anonymous> (C:\Users\---\Desktop\IVL\Discord\Bots\JavaScript\Maya\V2\index.js:5:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)

How can I resolve that?

**Comment by nathanjml** [comment]
works fine for me. 

I can almost guarantee you are not exporting whatever command it is trying to load properly -> 
use `module.exports = class ...`

**Comment by LwiDev** [comment]
@nathanjml 

https://pastebin.com/S4wYaMMy

**Comment by nathanjml** [comment]
> @nathanjml
> 
> https://pastebin.com/S4wYaMMy

Looks fine to me.
It could be a pathing issue with your folder structure. It might be better to pull the source code into your project and drop breakpoints to see what the object values are.

**Comment by Nedinator** [comment]
This is an issue with the user's code, not `djs-commands` itself. If you join {TheSourceCode} server (link in readme) you can get help there. Issue closed.
